---
# handlers file for roles/stack

- name: "restart nginx"
  service:
    name: "nginx"
    state: "restarted"
    enabled: "yes"

- name: "restart php-fpm"
  service:
    name: "php-fpm"
    state: "restarted"
    enabled: "yes"